import * as t from 'assert';
import { parseScript, recovery } from '../../../src/escaya';

describe('Expressions - Binary', () => {
  // Invalid cases
  for (const arg of [
    '({} /= x)',
    '({} |= x)',
    '({set * bar(x){})',
    '({static * bar(x){})',
    'x({set 123: x});',
    'x({set "abc": x});'
  ]) {
    it(`${arg}`, () => {
      t.throws(() => {
        parseScript(`${arg}`);
      });
    });
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        recovery(`${arg}`, 'recovery.js');
      });
    });
  }

  // Valid cases. Testing random cases to verify we have no issues with bit masks
  for (const arg of [
    '({   async *x(){}   })',
    '({   async *1(){}   })',
    'x({async foo(){}, bar(){}});',
    'x({async foo(){}});',
    'x({async [foo](){}});',
    'x({async foo(){}, async bar(){}});',
    'x({set [foo](a){}});',
    'x = {a, b} = y',
    '({y:y2} = {y:y2-2})',
    '({yield: 10 });',
    '({[foo]: x} = x) => y',
    '({[foo](){}, get [bar](){}});',
    '({ toast(a, b = 10, c) {}  });',
    '({ x([ a, b ]){} });',
    'x = { method() { }};;',
    'x = { [5 + 5]: foo }',
    '({get [x]() {}, set [x](v) {}});',
    '({a:  b.c })',
    '({a:  b.c  = d })',
    '({a:  b.c  = d  ? e : f })',
    'x({a:b=x}=y);',
    'x({a:b, c}=obj);',
    'x({a, c:d}=obj);',
    's = {s: true}',
    '({ a, b: x })',
    '({key: {}})',
    '({key: {a} = x})',
    '({a:b}=obj);',
    '({1:  {}.b ? c : d })',
    '({ a: {prop: 1}.prop } = {})',
    '({1:  + b })',
    '({[a]:  + b })',
    '({a:  + b })',
    '({...(obj)} = foo)',
    '({...(obj)} = foo),({...obj} = foo),({...obj.x} = foo),({...{}.x} = foo),({...[].x} = foo)',
    '({async})',
    '({async: await})',
    '({async: (await) ? yield : foo})',
    '({async: true})',
    '({async() { }})',
    '({async foo() { }})',
    '({foo() { }})',
    '({x, y, z () {}})',
    '({async delete() {}})',
    '({async [foo](){}})',
    '({async 100(){}})',
    '({throw(x, y) {}});',
    '({package(x, y) {}});',
    '({package(x, y) {}});',
    '({this(x, y) {}});',
    '({switch(x, y) {}});',
    '({}=x);',
    '({a:v=b}=c);',
    '({a=b}=c);',
    'x({[a]:b}=obj);',
    '({key: bar = x})',
    'x = {x: a}',
    '({f: function({x} = {x: 10}) {}});',
    '({f({x} = {x: 10}) {}});',
    'function x(a, { b }){};',
    '(function x({ a, b }){});',
    '(let[a] = b);',
    '({...obj}) => {}',
    '({a,...obj} = foo)',
    '({...obj} = foo)',
    'x ={ x = 1 }= z',
    'x ={ x: [ x ] } = { x: undefined }= z',
    '[{x : [{y:{z = 1}, z1 = 2}] }, {x2 = 3}, {x3 : {y3:[{z3 = 4}]}} ] = [{x:[{y:{}}]}, {}, {x3:{y3:[{}]}}];',
    '({ z : { __proto__: x, __proto__: y } = z })',
    '({ async(x, y) {}});',
    '[{a: b} = [c]]',
    '({ x } = (y));',
    '({ typeof(x, y) {}});',
    '({ x() {}, x: 1});',
    '({ *x() {}, get x() {}});',
    '({ x() {}, y() {}, x() {} })',
    '({ x() {}, x: 1 })',
    '({ x: 1, x() {} })',
    '({ x: 1, *x() {} })',
    'x({a:b, c}=obj);',
    'x({a=b}=c);',
    'x({a:v=b}=c);',
    '({"x": y+z})',
    '({"x": [y]})',
    '({"x": [y]} = x)',
    '({"x": [y]}) => x',
    '({"x": [y + x]})',
    '({"x": [y].slice(0)})',
    '({"x": {y: z}})',
    '({"x": {y: z}} = x)',
    '({"x": {a: y + x}})',
    '({"x": {a: y + x}.slice(0)})',
    '({"x": 600})',
    'x({[a]:b}=obj);',
    'x({[a]:b, [15]:d}=obj);',
    'x, {foo, bar} = doo',
    'x, {foo = y, bar} = doo',
    '({a, b} = c = d)',
    'a={"b":c=d}',
    's = {"foo": this}',
    '({x:let} = null)',
    '({x:let})',
    'x({"a":b}=obj);',
    '({x:let}) => null',
    'x({set "foo"(a){}});',
    'x({set 123(a){}});',
    '({ a = 42, [b]: c.d } = e);',
    '({790: null})',
    'x({foo(){}, *bar(){}});',
    'x({*set(){}});',
    '({   async *[ha+ha](){}   })',
    'x({async * foo(){}, bar(){}});',
    '({...a, obj: x})',
    '({...{}})',
    '({...obj,})',
    '({...a})',
    '({...obj,})',
    '({a: {b} = c})',
    'x = {10: y}',
    '({...a} = x)',
    '({...[a, b]})',
    '[{x:x = 1, y:y = 2}, [a = 3, b = 4, c = 5]] = {};',
    '({[foo()] : (z)} = z = {});',
    '({a: 1, a: 2})',
    '({b: x, a: 1, a: 2})',
    '({x=1} = {});',
    '({foo: typeof x});',
    '({foo: true / false});',
    'x({a}=obj);',
    'x({a:b}=obj);',
    'x({a, b}=obj);',
    'x({a:b, c:d}=obj);',
    'x({a, c:d}=obj);',
    '({eval} = x);',
    `x = { ...y }`,
    `x = { ...z = y}`,
    `x = { ...y, b: 1}`,
    `x = { a: 1, ...y, b: 1}`,
    '({eval});',
    '({eval = x} = y)',
    'x = {300: x}',
    '({[foo]: x} = y)',
    '({...x=y})',
    '({...x+y})',
    '({...x, ...y});',
    '({...x.y} = z)',
    '({...x, y});',
    '([{x = y}] = z)',
    '[{x = y}] = z',
    'x = {...y}',
    'x = {...a + b}',
    'x = {...[a, b]}',
    'x = {...{a, b}}',
    'x = {...a,}',
    'x = {...y, b}',
    'x = {a, ...y, b}',
    'z = {x, ...y}',
    'x = {...a, ...b}',
    'x({* foo(){},*bar(){}});',
    'x({[foo](){}, get [bar](){}});',
    'x({get [foo](){}});',
    'x({get [foo](){}, get [bar](){}});',
    'x({get foo(){}});',
    'x({get foo(){}, get bar(){}});',
    'x({get "foo"(){}});',
    'x({get 1(){}});',
    'x({get 0x234241(){}});',
    'x({get 0b001(){}});',
    'x({get 0o4567(){}});',
    '({typeof: x} = y);',
    'x({async get(){}});',
    '({async, foo})',
    'x({a:b, c:d}=obj);',
    'x({a, b}=obj);',
    'o = {key: bar.foo + x}',
    'x({[a]:b}=obj);',
    'x({[a]:b, [15]:d}=obj);',
    '({ [key++]: y, ...x } = { 1: 1, a: 1 })',
    '({ [++key]: y, [++key]: z, ...rest} = {2: 2, 3: 3})',
    '({ [left()]: y, ...x} = right())',
    '({ [(() => 1)()]: a, ...rest } = { 1: a })',
    '({ [1]: bar, ...rest } = foo)',
    '({topLeft: {x: x1, y: y1}, bottomRight: {x: x2, y: y2}} = rect)',
    '({ 3: foo, 5: bar } = [0, 1, 2, 3, 4, 5, 6])',
    '({ [fn()]: x, ...y } = z)',
    '({ident})',
    '({key: a.b} = c)',
    '({123: expr})',
    '({123: a.b} = c)',
    '({[key]: expr})',
    '({[key]: a.b} = c)',
    '({[1.2]: "A", [1e55]: "B", [0.000001]: "C", [-0]: "D", [Infinity]: "E", [-Infinity]: "F",[NaN]: "G", });',
    '({get ["a"]() {}})',
    '({set ["a"](x) {}})',
    '({set [0](x) {}})',
    '({set [0](x) { super.m("b", v); }})',
    '({set [0](x) { super.m("1", v); }})',
    '({...key = x})',
    '({...key.prop} = x)',
    'x = {ident,}',
    '({ ident: x })',
    '(x = {eval})',
    '({ a, b: x })',
    '({ident = x} = y)',
    '({a: {b: c} = 0})',
    '({a: {a: b.x} = 0})',
    '({a: {b} = 0})',
    '({a: {b}})',
    '({a: {b}, c})',
    '({a: [b.x] = 0})',
    '({a: [b] = 0})',
    '({a: (b.x) = 0} = 1)',
    '({a: (b) = 0} = 1)',
    '({ ...async () => { }})',
    'x = {get:b}',
    'x = {async:b}',
    'x = {a, b}',
    'x = {a, b} = x',
    '({x: async (y,w) => z})',
    '([ { x : foo()[y] } ])',
    '([ { x : x.y } ])',
    '[ { x : foo().y = 10 } = {} ]',
    '[ { x : y = 10 } = {} ]',
    '[{ x, y, z } = { x: 44, y: 55, z: 66 }]',
    '({ x: (y) = [] })',
    '[ { x : foo()[y] = 10 } = {} ]',
    '[ { x : x.y = 10 } = {} ]',
    '({*id() {}})',
    '({*await() {}})',
    '({ async get(){} })',
    '({ method(x = y, y) {} })',
    '({ async *method(...a) {} })',
    '({ if: 4 })',
    '({ eval: 7 })',
    '({async foo() {}})',
    '({ async static(){} })',
    '({ async : 0 })',
    '[{eval}.x] = [];',
    '([ { x : y } ])',
    '({ __proto__: 2 })',
    '({ x, y, z () {} })',
    '({ method(a,) {} })',
    '({ foo: 1, foo: 2 })',
    '({ async *method(x, y = x, z = y) {} })',
    '({ async *method([[...x] = function() {}()] = [[2, 1, 3]]) {} })',
    '({ async *method([[x, y, z] = [4, 5, 6]] = [[7, 8, 9]]) {} })',
    '({ async *method([...x]) {} })',
    '({ async *method([x]) {} })',
    '({ async *method([[,] = g()]) {} })',
    'x = {*"foo"(){}}',
    'x = {*123(){}}',
    'x = {*[foo](){}}',
    'x = {* foo(){},*bar(){}}',
    'x = {* foo(){}, bar(){}}',
    'x = {foo(){}, *bar(){}}',
    'x = {get foo(){}}',
    'x = {get get(){}}',
    'x = {get foo(){}, get bar(){}}',
    'x = {get foo(){}, bar(){}}',
    'x = {foo(){}, get bar(){}}',
    'x = {get [foo](){}}',
    'x = {get [foo](){}, get [bar](){}}',
    'x = {get [foo](){}, [bar](){}}',
    'x = {[foo](){}, get [bar](){}}',
    'x = {get 123(){}}',
    'x = {set foo(a){}}',
    'x = {set get(a){}}',
    'x = {foo: typeof x}',
    'x = {foo: true / false}',
    'x = {await}  = x',
    'x = {eval}',
    'x = {"x": [y]}',
    'x = {"x": [y]} = x',
    'x = {"x": [y + x]}',
    'x = {"x": [y].slice(0)}',
    'x = {"x": {y: z}}',
    'x = {"x": {y: z}} = x',
    'x = {"x": {a: y + x}}',
    'x = {"x": {a: y + x}.slice(0)}',
    'x = {"x": 600}',
    'x = {"x": 600..xyz}',
    'x = {...y}',
    'x = {x, ...y}',
    'x = {...a=b}',
    'x = {a, ...y, b}',
    'x = {...y, b}',
    'x = {get "foo"(){}}',
    'a = { x: y = function x() {}, x: fn = function() {} } = b',
    'a = { w, a: x } = b',
    'a = {...src.y.x} = b',
    'a = { y: x = 1 } = b',
    'a = { y = function x() {}, fn = function() {} } = b',
    'a = { w, x, y } = b',
    'a = { w, x, y = a ? x : b } = b',
    'a = { w, x, y = c } = b',
    'a = { w, x = b, y } = b',
    'a = { x: x[yield] } = b',
    'a = { x: [ x ] } = b',
    'a = { x: [x = yield] } = b',
    'a = { x: { x = yield } } = b',
    'a = { x: { y } } = b',
    'a = {...rest} = b',
    'a = {...src.y} = b',
    'a = {...src.y.x} = b',
    'x = { [a]: { "a": { "a": [] ? a : b } } }',
    'x = { [a]: {x} = y }',
    'x = { [a]: {x} = y.z }',
    'x = { [a]: [x] = y.z }',
    'x = { "a": [([] ? a : b.c[d])] / 2 }',
    'x = { "a": { "a": { "a": [] ? a : b } } }',
    'x = { "a": {x} = y }',
    'x = { "a": {x} = y.z }',
    'x = { "a": [x] = y.z }',
    '(x = { a: {x} = y }) / y.z',
    '(x = { a: x = y }) / y.z',
    '(x = { a: (x) = y }) / y.z',
    '(x = { a: x = (y) }) / y.z',
    '(x = { a: (x = (y)) }) / y.z',
    '(x = { "a": {x} = y }) / y.z',
    '(x = { "a": x = y }) / y.z',
    '(x = { "a": (x) = y }) / y.z',
    '(x = { "a": x = (y) }) / y.z',
    '(x = { "a": (x = (y)) }) / y.z',
    '(x = { [a]: {x} = y }) / y.z',
    '(x = { [a]: x = y }) / y.z',
    '(x = { [a]: (x) = y }) / y.z',
    '(x = { [a]: x = (y) }) / y.z',
    '(x = { [a]: (x = (y)) }) / y.z',
    'x = { "a": ([] ? a : b.c[d]) }',
    'x = {"d": {}[d] += a}',
    'x = {d: {}[d] += a}',
    'x = x = {[d]: {}[d] += a}',
    'x = { "a": [] ? a : b.c[d] }',
    'x = { "a": [] ? a : b / 2 - 2}',
    'x = { "a": [] ? a : b }',
    'x = {d: {}[d] += a}',
    'x = {"string": {}[d] += a}',
    'x = {["d"]: {}[d] += a}',
    '({ key: bar + x })',
    '({ key: bar/x })',
    '({ key: bar, foo: zoo })',
    '({ } = { })',
    '({  ...undefined })',
    '({  ...1 in {} })',
    '({ set foo(b){}, set bar(d){} })',
    '({ set foo(c){}, bar(){} })',
    '({ foo: typeof x })',
    '({ foo: true / false })',
    '({ ...y  })',
    '({ a: 1, ...y  })',
    '({  b: 1, ...y  })',
    '({ a: 1, ...y, b: 1 })',
    '({ ...1 })',
    '({ set foo(v) {} })',
    '({ 1: 1, 2: 2 })',
    '({ async 100(){} })',
    '({ method({ arrow = () => {} }) {} })',
    '({ method({ x: y, }) {} })',
    '({ async *method([x] = g[Symbol.iterator] = function() {}) {} })',
    '({ async *method([...x] = {}) {} })',
    '({ async *method([...async] = {}) {} })',
    '({ async *method({ w: [x, y, z] = [4, 5, 6] } = {}) {} })',
    '({ async *method({ x: y = thrower() } = {}) {} })',
    '({ async *method([x = 23]) {} })',
    '({ async *method([_, x]) {} })',
    '({ [++counter]: ++counter, [++counter]: ++counter, [++counter]: ++counter, [++counter]: ++counter })',
    '({ async *method(a, b,) {} })',
    '({ eval: 7 })',
    '({ if: 4 })',
    '({ foo: bar = 5 + baz })',
    '({ get foo() {} })',
    '({ a,1:b })',
    '({ 1:a,b })',
    '({ foo: 1, get foo() {} })',
    '({ 1: 1, get 1() {} })',
    'x = {async(){}}',
    '({ method(a, b,) {} })',
    '({ method(x = y, y) {} })',
    '({ async method(x, y = x, z = y) {} })',
    '({ *id() {} })',
    '({ *[anonSym]() {} })',
    '({ *method(a,) {} })',
    '({ async static(){} })',
    '({}=x);',
    '({a:v=b}=c);',
    '({...{}})',
    '({...a, obj: x})',
    '({obj: x, ...a})',
    '({obj, ...a})',
    '({catch: x});',
    '({...obj,})',
    '({...obj,})',
    's = {foo: yield}',
    's = {foo: yield / x}',
    's = {foo: yield /x/g}',
    'wrap({get 123(){}});',
    '({get await(){}});',
    '({await: x}) => x;',
    '({async: x}) => x;',
    '({async(){}});',
    'x({get "foo"(){}});',
    'x({async} = x);',
    'x({get} = x);',
    '({x} = foo )',
    'x = {get} = x',
    'x = {a:b, c:d}',
    'x = {a, c:d}',
    'x = {a, c:d} = x',
    'x = {a:b, c} = x',
    '({ [a]: {} [a] })',
    'x = {15:b}',
    'x = {1:b, 0:d}',
    'x = {"a":b}',
    'x = {"a":b, "c":d}',
    'x = {[a]:b}',
    'x = {[a]:b, [15]:d}',
    'x = { *a() {} }',
    'x = {0(){}}',
    'x = {"foo"(){}}',
    'x = {0b001001: y}',
    'x = {10: y}',
    'x = {async foo(){}}',
    'x = {async async(){}}',
    'x = {async "foo"(){}}',
    'x = {async 100(){}}',
    'x = {async [foo](){}}',
    'x = {async foo(){}, async bar(){}}',
    'x = {async foo(){}, bar(){}}',
    'x = {foo(){}, async bar(){}}',
    'x = {*foo(){}}',
    'x = {*get(){}}',
    'x = {*set(){}}',
    'x = {*async(){}}',
    '({ *method([[x, async, z] = [4, 5, 6]]) {} })',
    '({eval});',
    '({async x() {}});',
    '({async *x() {}});',
    '({async get() {}});',
    '({get x() {}});',
    '({set x(y) {}});',
    '({get() {}});',
    '({set() {}});',
    '({async() {}});',
    '({await() {}});',
    '({async = async} = x);',
    '({async});',
    '({x});',
    '([a,,...rest] = {})',
    '({} = 0);',
    '({y}) => x;',
    '({ a: 1 }).a === 1',
    '({ responseText: text } = res)',
    '(({a = {b} = {b: 42}}) => a.b)({})',
    '({ x : [ y = 10 ] = {} })',
    '({ x : [ foo().y = 10 ] = {} })',
    '({ x : [ foo()[y] = 10 ] = {} })',
    '({ x : [ y.z = 10 ] = {} })',
    '({ x : [ y[z] = 10 ] = {} })',
    '({ x : x, y : y })',
    '({ x : y, ...z })',
    '({ x : y = 1, ...z })',
    '({...x})',
    '({x, ...y})',
    '({x = 1} = {});',
    '({x, y = 1, z = 2} = {});',
    'x = {__proto__(){}, __proto__: 2}',
    'x = {__proto__(){}, __proto__(){}}',
    'x = {async __proto__(){}, *__proto__(){}}',
    '({x} = 0)',
    '({x,} = 0)',
    '({x,y,} = 0)',
    '({x,y} = 0)',
    '({x = 0} = 1)',
    '({x = 0,} = 1)',
    '({x: y = z = 0} = 1)',
    '({x: [y] = 0} = 1)',
    '({a:let} = 0);',
    '({let} = 0);',
    '({a:yield} = 0);',
    '({yield} = 0);',
    '({yield = 0} = 0);',
    '(a) = {}',
    '({x: ((y, z) => z).x})',
    '({ ...d.x })',
    '({ x: (foo.bar) })',
    '({foo: y, a:{bar: x}}) => x;',
    '({y, a:{x}}) => x;',
    '({b, c, d, ...{a} })',
    '({a, ...b} = {})',
    '[a,b=0,[c,...a[0]]={}]=0;',
    '(a.b = {});',
    '({ x: [ x ] } = { x: null });',
    '[{a=0},{a=0}] = 0',
    '({a: (b) = c} = [2])',
    '({...x = y, y})',
    '({ident: [foo].length} = x)',
    '({ident: [foo].length = x} = x)',
    '({a:b,...obj}) => {}',
    '({x, ...y} = {x, ...y})',
    '([ { x : foo().y } ])',
    '({ident: a[b]})',
    '({ident: a(b)})',
    '({ident: [],})',
    '({ident: ident = expr})',
    '({ident: (ident) = expr})',
    '({ident: a.b = expr})',
    '({ident: a[b] = expr})',
    '({ident: [] = expr,})',
    '({ident: {} = expr,})',
    'o = {key: bar + x}',
    'o = {key: bar = x}',
    'o = {key: bar.foo + x}',
    'o = {a: b} = d',
    'x = {x: a}',
    'o = {key: eval = a}',
    'o = {key: bar = a}',
    '({foo: true ** false});',
    '({eval} = x)',
    '({await})',
    '({ a, b: x })',
    'x({a:b, c});',
    'x({a:b, c} = y);',
    'x({a});',
    'x({set:b});',
    'x({a, b});',
    'foo({c=3} = {})',
    '({[a]:b})',
    '({get get(){}});',
    '({set set(x){}});',
    '({get foo(){}});',
    'x = { y = function x() {}, fn = function() {} }= z',
    '([a,,...rest] = {})',
    'function a({x: y, z: { a: b } }) {};',
    '({var: x} = 0)',
    '({[a]:  {}.b ? c : d })',
    '({a:  {}.b = c ? d : e })',
    '({a:  {}.b ? c : d })',
    '({a: (a).b ? c : d })',
    'x({1:b, 2:d});',
    'x = ({[a]:b});',
    'x = ({[a]:b, [15]:d});',
    '({[a]:b}=obj);',
    'x = {__proto__: a, __proto__: b} = y',
    '({__proto__: a, __proto__: b} = x)',
    '({...a}) => x',
    'x({get});',
    'x({static});',
    'x({a, c:d});',
    'x({set:b});',
    'x({a});',
    'x({a:b, c:d});',
    '({ async async(){} });',
    '({ async case(){} });',
    '({ async false(){} });',
    '({get arguments(){}});',
    '({arguments: x} = y);',
    'x({"a":b, "c":d});',
    'x({1:b, 0:d});',
    'x({15:b});',
    'x({foo(){}, async bar(){}});',
    'x= { get prototype(){} }',
    'x= { set prototype(x){} }',
    'x= { async prototype(){} }',
    'x({async * foo(){}, bar(){}});',
    'x({*"foo"(){}});',
    'x({[a]:b, [15]:d});',
    '({...{}})',
    `x = {
      *""() {},
    }`
  ]) {
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseScript(`${arg}`);
      });
    });
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        recovery(`${arg}`, 'recovery.js');
      });
    });
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        recovery(`${arg}`, 'recovery.js', { module: true });
      });
    });
  }
});
