import * as t from 'assert';
import { parseModule } from '../../../src/escaya';

describe('Module - Export', () => {
  // Invalid cases
  for (const arg of [
    'export let [.x] = obj;',
    'export let {x}, {y} = z;',
    'export let {x:y=z}, {a:b=c} = obj;',
    'export let {,} = obj;',
    'export * as x";',
    'export * as x from',
    'export * as x from 1',
    'export * as x from abc',
    'export foo;',
    'export let [foo];',
    //'export var let = x;',
    'export const foo = x foo',
    'export async function() {}',
    //'export default async function() { yield; }',
    //'export default async function() { yield = 1; }',
    //'export var await;',
    'export let foo = x foo',
    'export default await x',
    'export **= from "f";',
    'export {x, y} from "x" foo',
    'var foo; export {[foo](){}}',
    'var foo; export {[foo]}',
    'var foo; export {foo: new}',
    'var foo; export {foo(){}}',
    'var foo, bar; export {foo, ...bar}',
    'var foo, bar, x; export {{foo: x}}',
    //'export {new}',
    'export class () {}',
    'export var {[x]} = z;',
    'export var {[x]};',
    // 'export default async function() { yield = 1; }',
    // 'export default async function() { yield; }',
    // 'export const await = 5',
    'export { , };',
    'export default let x = 7;',
    'export default const x = 7;',
    'export *;',
    'export * from;',
    'export { Q } from;',
    'var a; export { a',
    'var a; export { a,',
    'var a; export { a, ;',
    'var a; export { a as };',
    'var a, b; export { a as , b};',
    'export }',
    'function foo() { }; export { , foo };',
    'function foo() { }; () => { export { foo }; }',
    'function foo() { }; try { export { foo }; } catch(e) { }',
    'export B, * as A, { C, D } from "test";',
    'export default;',
    'export default var x = 7;',
    'export default let x = 7;',
    'export default const x = 7;',
    'export * as;',
    'export * as foo;',
    'export * as foo from;',
    "export * as foo from ';",
    "export * as ,foo from 'bar'",
    'export class {}',
    'export class extends C {}',
    'export const const1;',
    'if (false) export default null;',
    'if (false) {} else export default null;',
    'for(var i=0; i<1; i++) export default null;',
    'while(false) export default null;',
    'var foo; export {foo: new foo}',
    'export default ...x = y',
    'export let ...x = y',
    'export {bar}, * from "bar";'
  ]) {
    it(`${arg}`, () => {
      t.throws(() => {
        parseModule(`${arg}`);
      });
    });
  }

  // Valid cases
  for (const arg of [
    'export let x = 0;',
    'export var y = 0;',
    'export const z = 0;',
    'export default class {}',
    'export {}',
    'let x; export {x as new}; import {new as foo} from "bar";',
    'var foo; export {foo as new}',
    'export default async function() {}',
    'export default async function f() {}',
    'var x,y; export {x as a, y as b}',
    'var x,y; export {x as a, y as b,}',
    'var x,y; export {x, y,}',
    'export var x',
    'export var x, y',
    'export * from "foo"',
    'export {x as a} from "foo"',
    'export {x,} from "foo"',
    'export default function f(){}',
    'export default async function(){}',
    'export * from "foo"',
    'export default () => x',
    "export * from 'p.js';",
    'export var foo;',
    'export {b as a}; export {a};',
    'export default class cName { valueOf() { return 45; } }',
    'export function goo() {};',
    'export let hoo;',
    'export let [foo] = arr, [bar] = arr2;',
    'export let [foo,,] = arr;',
    'export const joo = 42;',
    'export default (function koo() {});',
    'export var y = 0;',
    'export const z = 0;',
    'export class C { };',
    'export var j = 42;',
    'export let k = 42;',
    'export function l() {}',
    'export default function () {}',
    'export default class extends C {}',
    'export default 42',
    'var x; export default x = 7',
    "export { Q } from 'somemodule.js';",
    "export * from 'somemodule.js';",
    'var foo; export { foo as for };',
    "export { arguments } from 'm.js';",
    "export { for } from 'm.js';",
    "export { yield } from 'm.js'",
    "export { static } from 'm.js'",
    "export { let } from 'm.js'",
    'export default [];',
    'export default 42;',
    'export default { foo: 1 };',
    'export * from "foo";',
    'export {default} from "foo";',
    'export {foo as bar} from "foo";',
    'export function *foo () {}',
    'export default function(){}; export default function(){};',
    'export function a() {} export default function a() {}',
    'export let x = y, [x] = y;',
    'export function x(){}; export let [z] = y;',
    'export class f{}; async function f(){};',
    'export var a = x, b = y;',
    'export {a as b};',
    'export var foo = 1;',
    'var a; export { a as b, a as c };',
    'var a; export { a as await };',
    'var a; export { a as enum };',
    "export {thing}; import thing from 'a.js';",
    "export {thing}; import {thing} from 'a.js';",
    "export {thing}; import * as thing from 'a.js';",
    'export { x as y };',
    "export { a as b } from 'm.js';",
    "export * from 'p.js';",
    'export var foo;',
    'export function goo() {};',
    'export let hoo;',
    `export default class { constructor() {	foo() } a() {	bar()	}	}`,
    'export const joo = 42;',
    'export default (function koo() {});',
    'export { };',
    'export {get}; function get() {};',
    'function f() {}; f(); export { f };',
    'var a, b, c; export { a, b as baz, c };',
    'var d, e; export { d as dreary, e, };',
    'export default function f() {}',
    'export default function() {}',
    'export default function *a() {}',
    'export var foo = function () {};',
    'var a, b, c; export { a, b as baz, c };',
    'var d, e; export { d as dreary, e, };',
    'export default function f() {}',
    'export default function() {}',
    'export default function*() {}',
    'export default class C {}',
    'export default class {}',
    'export default class extends C {}',
    'export default 42',
    `export var x;
    x = 'Pass';`,
    'var x; export default x = 7',
    "export { Q } from 'somemodule.js';",
    "export * from 'somemodule.js';",
    'var foo; export { foo as for };',
    "export { arguments } from 'm.js';",
    "export { for } from 'm.js';",
    "export { yield } from 'm.js'",
    "export { static } from 'm.js'",
    "export { let } from 'm.js'",
    'var a; export { a as b, a as c };',
    'var a; export { a as await };',
    'var a; export { a as enum };',
    'var a, b, c; export { a, b as baz, c };',
    'var d, e; export { d as dreary, e, };',
    'export default function f() {}',
    'export default function() {}',
    'export default function *a() {}',
    'export let x = 0;',
    'export var y = 0;',
    'export const z = 0;',
    'export function func() { };',
    'export class C { };',
    'export { };',
    'function f() {}; f(); export { f };',
    'var a, b, c; export { a, b as baz, c };',
    'var d, e; export { d as dreary, e, };',
    'export default function f() {}',
    'export default function() {}',
    'export default function*() {}',
    'export default class C {}',
    'export default class {}',
    'export default class extends C {}',
    'export default 42',
    'var x; export default x = 7',
    "export * from 'somemodule.js';",
    'var foo; export { foo as for };',
    "export { arguments } from 'm.js';",
    "export { yield } from 'm.js'",
    'export default function f(){}; export {f};',
    'export default async function f(){}; export {f};',
    "export { static } from 'm.js'",
    "export { let } from 'm.js'",
    'var a; export { a as b, a as c };',
    'var a; export { a as await };',
    'var a; export { a as enum };',
    'export var document',
    'export var document = {}',
    'export var document',
    'export class Class {}',
    'export default 42',
    'export default class A {}',
    'export default (class{});',
    'export default /foo/',
    'export var namedOther = null;',
    'export var starAsVarDecl;',
    'export let starAsLetDecl;',
    'export const starAsConstDecl = null;',
    'export function starAsFuncDecl() {}',
    'export function* starAsGenDecl() {}',
    'export class starAsClassDecl {}',
    'export default class Foo {}++x',
    "export { x as y } from './y.js';\nexport { x as z } from './z.js';",
    "export { default as y } from './y.js';\nexport default 42;",
    'export default function(x) {};',
    'export default function () { };',
    'export default function _fn2 () { }',
    'class c { }; export default c',
    "var _ = { method: function() { return 'method_result'; }, method2: function() { return 'method2_result'; } }; export default _",
    'var a; export default a = 10;',
    'export default () => 3',
    'function _default() { }; export default _default',
    'export let a, [...x] = y',
    'export let [...x] = y',
    // Named generator function statement
    'function* g() { }; export default g',
    'class c { }; export default c',
    "var _ = { method: function() { return 'method_result'; }, method2: function() { return 'method2_result'; } }; export default _",
    'export default async \nfunction f(){}',
    'function foo() { }',
    "export const const2 = 'str';",
    'export const const3 = 3, const4 = 4;',
    'export const const5 = { }',
    'export const const6 = [ ]',
    'export {};',
    'class bar { }',
    'function* baz() { }',
    'function foobar() { }',
    "export var var1 = 'string';",
    "export default 'default';",
    'export var var2;',
    'export var var3 = 5, var4',
    'export var var5, var6, var7',
    'export default 1;',
    'var a; export default a = 10;',
    'function _default() { }; export default _default',
    'function* g() { }; export default g',
    'export function *g() { } if (true) { }',
    'export class c1 { } if (true) { }',
    'export default function* _gn2 () { } if (true) { }',
    'export default class _cl2 { } if (true) { }',
    'export default function _fn2 () { } if (true) { }',
    'class c { }; export default c',
    'export function a() {} export default function a() {}',
    'export function f(){}; export {f};',
    'export function f(){}; export {f};',
    'export class f {} export {f};',
    'export {x}; export class y {};',
    'export const x = y; export {f};',
    'export let x = y; export {f};',
    'export {f}; export const x = y;',
    'export {f}; export async function f() {}',
    'export default x; export {y as default};',
    'var x, y; export default x; export {y as default};',
    'export async function f(){}; const z = foo;',
    'const f = foo; export async function z(){};',
    'export var foo; export let foo;',
    'export let foo; export let foo;',
    'export default async function(){} foo',
    'export default async function f(){} foo',
    'export default async function *(){} foo',
    'export default function *(){} foo',
    'export default function(){} foo',
    'export default function f(){} foo',
    'export function f(){} foo',
    'export function* f(){}',
    'export let [...x] = y',
    'export let {...x} = y',
    //'export const x',
    `export default x
    /y`,
    'export let x = 10, y = 20',
    'export {x}; var x;',
    'export default class {}',
    'export default class f {}',
    'export class f {}',
    'export default x;',
    // 'export const foo = async function() { }',
    'export function async() { }',
    'export function func() { };',
    'export let [foo] = arr, [bar] = arr2;',
    'export let [...foo] = obj;',
    'export let [foo, ...bar] = obj;',
    'export { };',
    'export function set(x) { value = x };',
    'export let value = 0;',
    'export default function*() {}',
    'export function foo() { return 42 }',
    'export default 42;',
    'export let a = 1;',
    'export function set_a(x) { a = x };',
    'export function get_a() { return a };',
    'export {get}; function get() {};',
    'export default x;',
    'export default async function *(){} foo',
    'export default async function *f(){} foo',
    'export async function *f(){} foo',
    'export function* v() { return 40 }',
    'export var w = 41;',
    'export let x = 42;',
    'export const z = "hello world";',
    'function f() {}; f(); export { f };',
    'export let x = 0;',
    "export { a as b } from 'm.js';",
    "export * from 'p.js';",
    'export var foo;',
    'export function goo() {};',
    'export default (1 + 2);',
    'export let hoo;',
    'export const joo = 42;',
    'export default (function koo() {});',
    'export var y = 0;',
    'export const z = 0;',
    'export function func() { };',
    'export { };',
    'export function foo () { return "foo"; }',
    'export const boo = 5;',
    'import {ns} from "three";',
    'export let x = 0;',
    'export var y = 0;',
    'export const z = 0;',
    'export default x;',
    'export function func() { };',
    'var x; export default x = 7',
    "export { Q } from 'somemodule.js';",
    "export * from 'somemodule.js';",
    'var foo; export { foo as for };',
    "export { arguments } from 'm.js';",
    "export { for } from 'm.js';",
    "export { yield } from 'm.js'",
    "export { static } from 'm.js'",
    "export { let } from 'm.js'",
    "export * as arguments from 'm.js'",
    "export * as await from 'm.js'",
    "export * as default from 'm.js'",
    "export * as foo from 'm.js'",
    "export * as for from 'm.js'",
    "export * as let from 'm.js'",
    "export * as static from 'm.js'",
    "export * as yield from 'm.js'",
    'export default [];',
    'export default 42;',
    'export default { foo: 1 };',
    'export * from "foo";',
    'export * as A from "test";',
    'export {default} from "foo";',
    'export {foo as bar} from "foo";',
    'export function *foo () {}',
    'export function x(){}; export let [z] = y;',
    'export var a = x, b = y;',
    // 'export const yamtniufvkr = (eval)(...((null)[(this)]), ...(2e308), true), dujqtdq = (new ({eval, mÝ: eval, eval, get [((null))]() {   }})(...((null)[((null))]), ...(((/[^$-[-]/gmuy).h))));',
    'export var foo = 1;',
    'var a; export { a as b, a as c };',
    'var a; export { a as await };',
    'var a; export { a as enum };',
    "export {thing}; import thing from 'a.js';",
    "export {thing}; import {thing} from 'a.js';",
    "export {thing}; import * as thing from 'a.js';",
    "export { a as b } from 'm.js';",
    "export * from 'p.js';",
    'export var foo;',
    'a <!-- b',
    'export function goo() {};',
    'export let hoo;',
    'export default function f() {}',
    'export default function *a() {}',
    'export var foo = function () {};',
    'var a, b, c; export { a, b as baz, c };',
    'var d, e; export { d as dreary, e, };',
    'export default function*() {}',
    'export default 42',
    `export var x;
  x = 'Pass';`,
    'var x; export default x = 7',
    "export { Q } from 'somemodule.js';",
    "export * from 'somemodule.js';",
    'var foo; export { foo as for };',
    "export { arguments } from 'm.js';",
    "export { for } from 'm.js';",
    "export { yield } from 'm.js'",
    "export { static } from 'm.js'",
    "export { let } from 'm.js'",
    'export var namedOther = null;',
    'export var starAsVarDecl;',
    'export let starAsLetDecl;',
    'export const starAsConstDecl = null;',
    'export function starAsFuncDecl() {}',
    'export function* starAsGenDecl() {}',
    'export default () => 3',
    'function _default() { }; export default _default',
    'export let a, [...x] = y',
    // 'export let [...x] = y',
    // Named generator function statement
    'function* g() { }; export default g',
    'export default async \nfunction f(){}',
    "export const const2 = 'str';",
    'export const const3 = 3, const4 = 4;',
    'export default 1;',
    'var a; export default a = 10;',
    'function _default() { }; export default _default',
    'function* g() { }; export default g',
    'export function *g() { } if (true) { }',
    'export let x = y, {...z} = y;',
    'export let x = y, [...z] = y;',
    'export default function () {}',
    'export var {x} = a, {y} = obj;',
    'export var {x} = a, y = obj;',
    'export default () => {}',
    'export { encrypt }\nvar encrypt',
    'function encrypt() {} let decrypt; export { encrypt, decrypt }',
    'export const const5 = { }',
    'export const const6 = [ ]',
    'function x() {  "a" ? ((this)) : ((true));  }',
    'export {};',
    "export var var1 = 'string';",
    "export default 'default';",
    'export var var2;',
    'export var var3 = 5, var4',
    'export var var5, var6, var7'
  ]) {
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseModule(`${arg}`);
      });
    });
  }
});
