import { Chars } from './chars';
import { Token } from '../token';

export const oneCharTokens = [
  /*   0 - Null               */ Token.Unknown,
  /*   1 - Start of Heading   */ Token.Unknown,
  /*   2 - Start of Text      */ Token.Unknown,
  /*   3 - End of Text        */ Token.Unknown,
  /*   4 - End of Transm.     */ Token.Unknown,
  /*   5 - Enquiry            */ Token.Unknown,
  /*   6 - Acknowledgment     */ Token.Unknown,
  /*   7 - Bell               */ Token.Unknown,
  /*   8 - Backspace          */ Token.Unknown,
  /*   9 - Horizontal Tab     */ Token.WhiteSpace,
  /*  10 - Line Feed          */ Token.LineFeed,
  /*  11 - Vertical Tab       */ Token.WhiteSpace,
  /*  12 - Form Feed          */ Token.WhiteSpace,
  /*  13 - Carriage Return    */ Token.CarriageReturn,
  /*  14 - Shift Out          */ Token.Unknown,
  /*  15 - Shift In           */ Token.Unknown,
  /*  16 - Data Line Escape   */ Token.Unknown,
  /*  17 - Device Control 1   */ Token.Unknown,
  /*  18 - Device Control 2   */ Token.Unknown,
  /*  19 - Device Control 3   */ Token.Unknown,
  /*  20 - Device Control 4   */ Token.Unknown,
  /*  21 - Negative Ack.      */ Token.Unknown,
  /*  22 - Synchronous Idle   */ Token.Unknown,
  /*  23 - End of Transmit    */ Token.Unknown,
  /*  24 - Cancel             */ Token.Unknown,
  /*  25 - End of Medium      */ Token.Unknown,
  /*  26 - Substitute         */ Token.Unknown,
  /*  27 - Escape             */ Token.Unknown,
  /*  28 - File Separator     */ Token.Unknown,
  /*  29 - Group Separator    */ Token.Unknown,
  /*  30 - Record Separator   */ Token.Unknown,
  /*  31 - Unit Separator     */ Token.Unknown,
  /*  32 - Space              */ Token.WhiteSpace,
  /*  33 - !                  */ Token.Negate,
  /*  34 - "                  */ Token.StringLiteral,
  /*  35 - #                  */ Token.PrivateName,
  /*  36 - $                  */ Token.Identifier,
  /*  37 - %                  */ Token.Modulo,
  /*  38 - &                  */ Token.BitwiseAnd,
  /*  39 - '                  */ Token.StringLiteral,
  /*  40 - (                  */ Token.LeftParen,
  /*  41 - )                  */ Token.RightParen,
  /*  42 - *                  */ Token.Multiply,
  /*  43 - +                  */ Token.Add,
  /*  44 - ,                  */ Token.Comma,
  /*  45 - -                  */ Token.Subtract,
  /*  46 - .                  */ Token.Period,
  /*  47 - /                  */ Token.Divide,
  /*  48 - 0                  */ Token.NumericLiteral,
  /*  49 - 1                  */ Token.NumericLiteral,
  /*  50 - 2                  */ Token.NumericLiteral,
  /*  51 - 3                  */ Token.NumericLiteral,
  /*  52 - 4                  */ Token.NumericLiteral,
  /*  53 - 5                  */ Token.NumericLiteral,
  /*  54 - 6                  */ Token.NumericLiteral,
  /*  55 - 7                  */ Token.NumericLiteral,
  /*  56 - 8                  */ Token.NumericLiteral,
  /*  57 - 9                  */ Token.NumericLiteral,
  /*  58 - :                  */ Token.Colon,
  /*  59 - ;                  */ Token.Semicolon,
  /*  60 - <                  */ Token.LessThan,
  /*  61 - =                  */ Token.Assign,
  /*  62 - >                  */ Token.GreaterThan,
  /*  63 - ?                  */ Token.QuestionMark,
  /*  64 - @                  */ Token.Unknown,
  /*  65 - A                  */ Token.Identifier,
  /*  66 - B                  */ Token.Identifier,
  /*  67 - C                  */ Token.Identifier,
  /*  68 - D                  */ Token.Identifier,
  /*  69 - E                  */ Token.Identifier,
  /*  70 - F                  */ Token.Identifier,
  /*  71 - G                  */ Token.Identifier,
  /*  72 - H                  */ Token.Identifier,
  /*  73 - I                  */ Token.Identifier,
  /*  74 - J                  */ Token.Identifier,
  /*  75 - K                  */ Token.Identifier,
  /*  76 - L                  */ Token.Identifier,
  /*  77 - M                  */ Token.Identifier,
  /*  78 - N                  */ Token.Identifier,
  /*  79 - O                  */ Token.Identifier,
  /*  80 - P                  */ Token.Identifier,
  /*  81 - Q                  */ Token.Identifier,
  /*  82 - R                  */ Token.Identifier,
  /*  83 - S                  */ Token.Identifier,
  /*  84 - T                  */ Token.Identifier,
  /*  85 - U                  */ Token.Identifier,
  /*  86 - V                  */ Token.Identifier,
  /*  87 - W                  */ Token.Identifier,
  /*  88 - X                  */ Token.Identifier,
  /*  89 - Y                  */ Token.Identifier,
  /*  90 - Z                  */ Token.Identifier,
  /*  91 - [                  */ Token.LeftBracket,
  /*  92 - \                  */ Token.EscapedIdentifier,
  /*  93 - ]                  */ Token.RightBracket,
  /*  94 - ^                  */ Token.BitwiseXor,
  /*  95 - _                  */ Token.Identifier,
  /*  96 - `                  */ Token.TemplateTail,
  /*  97 - a                  */ Token.Identifier,
  /*  98 - b                  */ Token.Identifier,
  /*  99 - c                  */ Token.Identifier,
  /* 100 - d                  */ Token.Identifier,
  /* 101 - e                  */ Token.Identifier,
  /* 102 - f                  */ Token.Identifier,
  /* 103 - g                  */ Token.Identifier,
  /* 104 - h                  */ Token.Identifier,
  /* 105 - i                  */ Token.Identifier,
  /* 106 - j                  */ Token.Identifier,
  /* 107 - k                  */ Token.Identifier,
  /* 108 - l                  */ Token.Identifier,
  /* 109 - m                  */ Token.Identifier,
  /* 110 - n                  */ Token.Identifier,
  /* 111 - o                  */ Token.Identifier,
  /* 112 - p                  */ Token.Identifier,
  /* 113 - q                  */ Token.Identifier,
  /* 114 - r                  */ Token.Identifier,
  /* 115 - s                  */ Token.Identifier,
  /* 116 - t                  */ Token.Identifier,
  /* 117 - u                  */ Token.Identifier,
  /* 118 - v                  */ Token.Identifier,
  /* 119 - w                  */ Token.Identifier,
  /* 120 - x                  */ Token.Identifier,
  /* 121 - y                  */ Token.Identifier,
  /* 122 - z                  */ Token.Identifier,
  /* 123 - {                  */ Token.LeftBrace,
  /* 124 - |                  */ Token.BitwiseOr,
  /* 125 - }                  */ Token.RightBrace,
  /* 126 - ~                  */ Token.Complement,
  /* 127 - Delete             */ Token.Unknown,
  /* 128 - Cc category        */ Token.Unknown,
  /* 129 - Cc category        */ Token.Unknown,
  /* 130 - Cc category        */ Token.Unknown,
  /* 131 - Cc category        */ Token.Unknown,
  /* 132 - Cc category        */ Token.Unknown,
  /* 133 - Cc category        */ Token.Unknown,
  /* 134 - Cc category        */ Token.Unknown,
  /* 135 - Cc category        */ Token.Unknown,
  /* 136 - Cc category        */ Token.Unknown,
  /* 137 - Cc category        */ Token.Unknown,
  /* 138 - Cc category        */ Token.Unknown,
  /* 139 - Cc category        */ Token.Unknown,
  /* 140 - Cc category        */ Token.Unknown,
  /* 141 - Cc category        */ Token.Unknown,
  /* 142 - Cc category        */ Token.Unknown,
  /* 143 - Cc category        */ Token.Unknown,
  /* 144 - Cc category        */ Token.Unknown,
  /* 145 - Cc category        */ Token.Unknown,
  /* 146 - Cc category        */ Token.Unknown,
  /* 147 - Cc category        */ Token.Unknown,
  /* 148 - Cc category        */ Token.Unknown,
  /* 149 - Cc category        */ Token.Unknown,
  /* 150 - Cc category        */ Token.Unknown,
  /* 151 - Cc category        */ Token.Unknown,
  /* 152 - Cc category        */ Token.Unknown,
  /* 153 - Cc category        */ Token.Unknown,
  /* 154 - Cc category        */ Token.Unknown,
  /* 155 - Cc category        */ Token.Unknown,
  /* 156 - Cc category        */ Token.Unknown,
  /* 157 - Cc category        */ Token.Unknown,
  /* 158 - Cc category        */ Token.Unknown,
  /* 159 - Cc category        */ Token.Unknown,
  /* 160 - Zs category (nbsp) */ Token.Unknown,
  /* 161 - Po category        */ Token.Unknown,
  /* 162 - Sc category        */ Token.Unknown,
  /* 163 - Sc category        */ Token.Unknown,
  /* 164 - Sc category        */ Token.Unknown,
  /* 165 - Sc category        */ Token.Unknown,
  /* 166 - So category        */ Token.Unknown,
  /* 167 - So category        */ Token.Unknown,
  /* 168 - Sk category        */ Token.Unknown,
  /* 169 - So category        */ Token.Unknown,
  /* 170 - Ll category        */ Token.Identifier,
  /* 171 - Pi category        */ Token.Unknown,
  /* 172 - Sm category        */ Token.Unknown,
  /* 173 - Cf category        */ Token.Unknown,
  /* 174 - So category        */ Token.Unknown,
  /* 175 - Sk category        */ Token.Unknown,
  /* 176 - So category        */ Token.Unknown,
  /* 177 - Sm category        */ Token.Unknown,
  /* 178 - No category        */ Token.Unknown,
  /* 179 - No category        */ Token.Unknown,
  /* 180 - Sk category        */ Token.Unknown,
  /* 181 - Ll category        */ Token.Identifier,
  /* 182 - So category        */ Token.Unknown,
  /* 183 - Po category        */ Token.Unknown,
  /* 184 - Sk category        */ Token.Unknown,
  /* 185 - No category        */ Token.Unknown,
  /* 186 - Ll category        */ Token.Identifier,
  /* 187 - Pf category        */ Token.Unknown,
  /* 188 - No category        */ Token.Unknown,
  /* 189 - No category        */ Token.Unknown,
  /* 190 - No category        */ Token.Unknown,
  /* 191 - Po category        */ Token.Unknown,
  /* 192 - Lu category        */ Token.Identifier,
  /* 193 - Lu category        */ Token.Identifier,
  /* 194 - Lu category        */ Token.Identifier,
  /* 195 - Lu category        */ Token.Identifier,
  /* 196 - Lu category        */ Token.Identifier,
  /* 197 - Lu category        */ Token.Identifier,
  /* 198 - Lu category        */ Token.Identifier,
  /* 199 - Lu category        */ Token.Identifier,
  /* 200 - Lu category        */ Token.Identifier,
  /* 201 - Lu category        */ Token.Identifier,
  /* 202 - Lu category        */ Token.Identifier,
  /* 203 - Lu category        */ Token.Identifier,
  /* 204 - Lu category        */ Token.Identifier,
  /* 205 - Lu category        */ Token.Identifier,
  /* 206 - Lu category        */ Token.Identifier,
  /* 207 - Lu category        */ Token.Identifier,
  /* 208 - Lu category        */ Token.Identifier,
  /* 209 - Lu category        */ Token.Identifier,
  /* 210 - Lu category        */ Token.Identifier,
  /* 211 - Lu category        */ Token.Identifier,
  /* 212 - Lu category        */ Token.Identifier,
  /* 213 - Lu category        */ Token.Identifier,
  /* 214 - Lu category        */ Token.Identifier,
  /* 215 - Sm category        */ Token.Unknown,
  /* 216 - Lu category        */ Token.Identifier,
  /* 217 - Lu category        */ Token.Identifier,
  /* 218 - Lu category        */ Token.Identifier,
  /* 219 - Lu category        */ Token.Identifier,
  /* 220 - Lu category        */ Token.Identifier,
  /* 221 - Lu category        */ Token.Identifier,
  /* 222 - Lu category        */ Token.Identifier,
  /* 223 - Ll category        */ Token.Identifier,
  /* 224 - Ll category        */ Token.Identifier,
  /* 225 - Ll category        */ Token.Identifier,
  /* 226 - Ll category        */ Token.Identifier,
  /* 227 - Ll category        */ Token.Identifier,
  /* 228 - Ll category        */ Token.Identifier,
  /* 229 - Ll category        */ Token.Identifier,
  /* 230 - Ll category        */ Token.Identifier,
  /* 231 - Ll category        */ Token.Identifier,
  /* 232 - Ll category        */ Token.Identifier,
  /* 233 - Ll category        */ Token.Identifier,
  /* 234 - Ll category        */ Token.Identifier,
  /* 235 - Ll category        */ Token.Identifier,
  /* 236 - Ll category        */ Token.Identifier,
  /* 237 - Ll category        */ Token.Identifier,
  /* 238 - Ll category        */ Token.Identifier,
  /* 239 - Ll category        */ Token.Identifier,
  /* 240 - Ll category        */ Token.Identifier,
  /* 241 - Ll category        */ Token.Identifier,
  /* 242 - Ll category        */ Token.Identifier,
  /* 243 - Ll category        */ Token.Identifier,
  /* 244 - Ll category        */ Token.Identifier,
  /* 245 - Ll category        */ Token.Identifier,
  /* 246 - Ll category        */ Token.Identifier,
  /* 247 - Sm category        */ Token.Unknown,
  /* 248 - Ll category        */ Token.Identifier,
  /* 249 - Ll category        */ Token.Identifier,
  /* 250 - Ll category        */ Token.Identifier,
  /* 251 - Ll category        */ Token.Identifier,
  /* 252 - Ll category        */ Token.Identifier,
  /* 253 - Ll category        */ Token.Identifier,
  /* 254 - Ll category        */ Token.Identifier,
  /* 255 - Ll category        */ Token.Identifier
];

export const leadingZeroChars = [
  /*   0 - Null               */ Chars.Unknown,
  /*   1 - Start of Heading   */ Chars.Unknown,
  /*   2 - Start of Text      */ Chars.Unknown,
  /*   3 - End of Text        */ Chars.Unknown,
  /*   4 - End of Transm.     */ Chars.Unknown,
  /*   5 - Enquiry            */ Chars.Unknown,
  /*   6 - Acknowledgment     */ Chars.Unknown,
  /*   7 - Bell               */ Chars.Unknown,
  /*   8 - Backspace          */ Chars.Unknown,
  /*   9 - Horizontal Tab     */ Chars.Unknown,
  /*  10 - Line Feed          */ Chars.Unknown,
  /*  11 - Vertical Tab       */ Chars.Unknown,
  /*  12 - Form Feed          */ Chars.Unknown,
  /*  13 - Carriage Return    */ Chars.Unknown,
  /*  14 - Shift Out          */ Chars.Unknown,
  /*  15 - Shift In           */ Chars.Unknown,
  /*  16 - Data Line Escape   */ Chars.Unknown,
  /*  17 - Device Control 1   */ Chars.Unknown,
  /*  18 - Device Control 2   */ Chars.Unknown,
  /*  19 - Device Control 3   */ Chars.Unknown,
  /*  20 - Device Control 4   */ Chars.Unknown,
  /*  21 - Negative Ack.      */ Chars.Unknown,
  /*  22 - Synchronous Idle   */ Chars.Unknown,
  /*  23 - End of Transmit    */ Chars.Unknown,
  /*  24 - Cancel             */ Chars.Unknown,
  /*  25 - End of Medium      */ Chars.Unknown,
  /*  26 - Substitute         */ Chars.Unknown,
  /*  27 - Escape             */ Chars.Unknown,
  /*  28 - File Separator     */ Chars.Unknown,
  /*  29 - Group Separator    */ Chars.Unknown,
  /*  30 - Record Separator   */ Chars.Unknown,
  /*  31 - Unit Separator     */ Chars.Unknown,
  /*  32 - Space              */ Chars.Unknown,
  /*  33 - !                  */ Chars.Unknown,
  /*  34 - "                  */ Chars.Unknown,
  /*  35 - #                  */ Chars.Unknown,
  /*  36 - $                  */ Chars.Unknown,
  /*  37 - %                  */ Chars.Unknown,
  /*  38 - &                  */ Chars.Unknown,
  /*  39 - '                  */ Chars.Unknown,
  /*  40 - (                  */ Chars.Unknown,
  /*  41 - )                  */ Chars.Unknown,
  /*  42 - *                  */ Chars.Unknown,
  /*  43 - +                  */ Chars.Plus,
  /*  44 - ,                  */ Chars.Unknown,
  /*  45 - -                  */ Chars.Hyphen,
  /*  46 - .                  */ Chars.Period,
  /*  47 - /                  */ Chars.Unknown,
  /*  48 - 0                  */ Chars.Zero,
  /*  49 - 1                  */ Chars.One,
  /*  50 - 2                  */ Chars.Two,
  /*  51 - 3                  */ Chars.Three,
  /*  52 - 4                  */ Chars.Four,
  /*  53 - 5                  */ Chars.Five,
  /*  54 - 6                  */ Chars.Six,
  /*  55 - 7                  */ Chars.Seven,
  /*  56 - 8                  */ Chars.Eight,
  /*  57 - 9                  */ Chars.Nine,
  /*  58 - :                  */ Chars.Unknown,
  /*  59 - ;                  */ Chars.Unknown,
  /*  60 - <                  */ Chars.Unknown,
  /*  61 - =                  */ Chars.Unknown,
  /*  62 - >                  */ Chars.Unknown,
  /*  63 - ?                  */ Chars.Unknown,
  /*  64 - @                  */ Chars.Unknown,
  /*  65 - A                  */ Chars.UpperA,
  /*  66 - B                  */ Chars.UpperB,
  /*  67 - C                  */ Chars.UpperC,
  /*  68 - D                  */ Chars.UpperD,
  /*  69 - E                  */ Chars.UpperE,
  /*  70 - F                  */ Chars.UpperF,
  /*  71 - G                  */ Chars.Unknown,
  /*  72 - H                  */ Chars.Unknown,
  /*  73 - I                  */ Chars.Unknown,
  /*  74 - J                  */ Chars.Unknown,
  /*  75 - K                  */ Chars.Unknown,
  /*  76 - L                  */ Chars.Unknown,
  /*  77 - M                  */ Chars.Unknown,
  /*  78 - N                  */ Chars.Unknown,
  /*  79 - O                  */ Chars.UpperO,
  /*  80 - P                  */ Chars.Unknown,
  /*  81 - Q                  */ Chars.Unknown,
  /*  82 - R                  */ Chars.Unknown,
  /*  83 - S                  */ Chars.Unknown,
  /*  84 - T                  */ Chars.Unknown,
  /*  85 - U                  */ Chars.Unknown,
  /*  86 - V                  */ Chars.Unknown,
  /*  87 - W                  */ Chars.Unknown,
  /*  88 - X                  */ Chars.UpperX,
  /*  89 - Y                  */ Chars.Unknown,
  /*  90 - Z                  */ Chars.Unknown,
  /*  91 - [                  */ Chars.Unknown,
  /*  92 - \                  */ Chars.Unknown,
  /*  93 - ]                  */ Chars.Unknown,
  /*  94 - ^                  */ Chars.Unknown,
  /*  95 - _                  */ Chars.Unknown,
  /*  96 - `                  */ Chars.Unknown,
  /*  97 - a                  */ Chars.LowerA,
  /*  98 - b                  */ Chars.LowerB,
  /*  99 - c                  */ Chars.LowerC,
  /* 100 - d                  */ Chars.LowerD,
  /* 101 - e                  */ Chars.LowerE,
  /* 102 - f                  */ Chars.LowerF,
  /* 103 - g                  */ Chars.Unknown,
  /* 104 - h                  */ Chars.Unknown,
  /* 105 - i                  */ Chars.Unknown,
  /* 106 - j                  */ Chars.Unknown,
  /* 107 - k                  */ Chars.Unknown,
  /* 108 - l                  */ Chars.Unknown,
  /* 109 - m                  */ Chars.Unknown,
  /* 110 - n                  */ Chars.LowerN,
  /* 111 - o                  */ Chars.LowerO,
  /* 112 - p                  */ Chars.Unknown,
  /* 113 - q                  */ Chars.Unknown,
  /* 114 - r                  */ Chars.Unknown,
  /* 115 - s                  */ Chars.Unknown,
  /* 116 - t                  */ Chars.Unknown,
  /* 117 - u                  */ Chars.Unknown,
  /* 118 - v                  */ Chars.Unknown,
  /* 119 - w                  */ Chars.Unknown,
  /* 120 - x                  */ Chars.LowerX,
  /* 121 - y                  */ Chars.Unknown,
  /* 122 - z                  */ Chars.Unknown,
  /* 123 - {                  */ Chars.Unknown,
  /* 124 - |                  */ Chars.Unknown,
  /* 125 - }                  */ Chars.Unknown,
  /* 126 - ~                  */ Chars.Unknown,
  /* 127 - Delete             */ Chars.Unknown
];

export const escapeChars = [
  /*   0 - Null               */ Chars.Unknown,
  /*   1 - Start of Heading   */ Chars.Unknown,
  /*   2 - Start of Text      */ Chars.Unknown,
  /*   3 - End of Text        */ Chars.Unknown,
  /*   4 - End of Transm.     */ Chars.Unknown,
  /*   5 - Enquiry            */ Chars.Unknown,
  /*   6 - Acknowledgment     */ Chars.Unknown,
  /*   7 - Bell               */ Chars.Unknown,
  /*   8 - Backspace          */ Chars.Unknown,
  /*   9 - Horizontal Tab     */ Chars.Unknown,
  /*  10 - Line Feed          */ Chars.LineFeed,
  /*  11 - Vertical Tab       */ Chars.Unknown,
  /*  12 - Form Feed          */ Chars.Unknown,
  /*  13 - Carriage Return    */ Chars.CarriageReturn,
  /*  14 - Shift Out          */ Chars.Unknown,
  /*  15 - Shift In           */ Chars.Unknown,
  /*  16 - Data Line Escape   */ Chars.Unknown,
  /*  17 - Device Control 1   */ Chars.Unknown,
  /*  18 - Device Control 2   */ Chars.Unknown,
  /*  19 - Device Control 3   */ Chars.Unknown,
  /*  20 - Device Control 4   */ Chars.Unknown,
  /*  21 - Negative Ack.      */ Chars.Unknown,
  /*  22 - Synchronous Idle   */ Chars.Unknown,
  /*  23 - End of Transmit    */ Chars.Unknown,
  /*  24 - Cancel             */ Chars.Unknown,
  /*  25 - End of Medium      */ Chars.Unknown,
  /*  26 - Substitute         */ Chars.Unknown,
  /*  27 - Escape             */ Chars.Unknown,
  /*  28 - File Separator     */ Chars.Unknown,
  /*  29 - Group Separator    */ Chars.Unknown,
  /*  30 - Record Separator   */ Chars.Unknown,
  /*  31 - Unit Separator     */ Chars.Unknown,
  /*  32 - Space              */ Chars.Unknown,
  /*  33 - !                  */ Chars.Unknown,
  /*  34 - "                  */ Chars.Unknown,
  /*  35 - #                  */ Chars.Unknown,
  /*  36 - $                  */ Chars.Unknown,
  /*  37 - %                  */ Chars.Unknown,
  /*  38 - &                  */ Chars.Unknown,
  /*  39 - '                  */ Chars.Unknown,
  /*  40 - (                  */ Chars.Unknown,
  /*  41 - )                  */ Chars.Unknown,
  /*  42 - *                  */ Chars.Unknown,
  /*  43 - +                  */ Chars.Unknown,
  /*  44 - ,                  */ Chars.Unknown,
  /*  45 - -                  */ Chars.Unknown,
  /*  46 - .                  */ Chars.Unknown,
  /*  47 - /                  */ Chars.Unknown,
  /*  48 - 0                  */ Chars.Zero,
  /*  49 - 1                  */ Chars.One,
  /*  50 - 2                  */ Chars.Two,
  /*  51 - 3                  */ Chars.Three,
  /*  52 - 4                  */ Chars.Four,
  /*  53 - 5                  */ Chars.Five,
  /*  54 - 6                  */ Chars.Six,
  /*  55 - 7                  */ Chars.Seven,
  /*  56 - 8                  */ Chars.Eight,
  /*  57 - 9                  */ Chars.Nine,
  /*  58 - :                  */ Chars.Unknown,
  /*  59 - ;                  */ Chars.Unknown,
  /*  60 - <                  */ Chars.Unknown,
  /*  61 - =                  */ Chars.Unknown,
  /*  62 - >                  */ Chars.Unknown,
  /*  63 - ?                  */ Chars.Unknown,
  /*  64 - @                  */ Chars.Unknown,
  /*  65 - A                  */ Chars.Unknown,
  /*  66 - B                  */ Chars.Unknown,
  /*  67 - C                  */ Chars.Unknown,
  /*  68 - D                  */ Chars.Unknown,
  /*  69 - E                  */ Chars.Unknown,
  /*  70 - F                  */ Chars.Unknown,
  /*  71 - G                  */ Chars.Unknown,
  /*  72 - H                  */ Chars.Unknown,
  /*  73 - I                  */ Chars.Unknown,
  /*  74 - J                  */ Chars.Unknown,
  /*  75 - K                  */ Chars.Unknown,
  /*  76 - L                  */ Chars.Unknown,
  /*  77 - M                  */ Chars.Unknown,
  /*  78 - N                  */ Chars.Unknown,
  /*  79 - O                  */ Chars.Unknown,
  /*  80 - P                  */ Chars.Unknown,
  /*  81 - Q                  */ Chars.Unknown,
  /*  82 - R                  */ Chars.Unknown,
  /*  83 - S                  */ Chars.Unknown,
  /*  84 - T                  */ Chars.Unknown,
  /*  85 - U                  */ Chars.Unknown,
  /*  86 - V                  */ Chars.Unknown,
  /*  87 - W                  */ Chars.Unknown,
  /*  88 - X                  */ Chars.Unknown,
  /*  89 - Y                  */ Chars.Unknown,
  /*  90 - Z                  */ Chars.Unknown,
  /*  91 - [                  */ Chars.Unknown,
  /*  92 - \                  */ Chars.Unknown,
  /*  93 - ]                  */ Chars.Unknown,
  /*  94 - ^                  */ Chars.Unknown,
  /*  95 - _                  */ Chars.Unknown,
  /*  96 - `                  */ Chars.Unknown,
  /*  97 - a                  */ Chars.Unknown,
  /*  98 - b                  */ Chars.LowerB,
  /*  99 - c                  */ Chars.Unknown,
  /* 100 - d                  */ Chars.Unknown,
  /* 101 - e                  */ Chars.Unknown,
  /* 102 - f                  */ Chars.LowerF,
  /* 103 - g                  */ Chars.Unknown,
  /* 104 - h                  */ Chars.Unknown,
  /* 105 - i                  */ Chars.Unknown,
  /* 106 - j                  */ Chars.Unknown,
  /* 107 - k                  */ Chars.Unknown,
  /* 108 - l                  */ Chars.Unknown,
  /* 109 - m                  */ Chars.Unknown,
  /* 110 - n                  */ Chars.LowerN,
  /* 111 - o                  */ Chars.Unknown,
  /* 112 - p                  */ Chars.Unknown,
  /* 113 - q                  */ Chars.Unknown,
  /* 114 - r                  */ Chars.LowerR,
  /* 115 - s                  */ Chars.Unknown,
  /* 116 - t                  */ Chars.LowerT,
  /* 117 - u                  */ Chars.LowerU,
  /* 118 - v                  */ Chars.LowerV,
  /* 119 - w                  */ Chars.Unknown,
  /* 120 - x                  */ Chars.LowerX,
  /* 121 - y                  */ Chars.Unknown,
  /* 122 - z                  */ Chars.Unknown,
  /* 123 - {                  */ Chars.Unknown,
  /* 124 - |                  */ Chars.Unknown,
  /* 125 - }                  */ Chars.Unknown,
  /* 126 - ~                  */ Chars.Unknown,
  /* 127 - Delete             */ Chars.Unknown
];
