// Constexpr cache table for character flags.
export const enum AsciiCharFlags {
  Unknown = 0,
  IsIdentifierStart = 1 << 0,
  IsIdentifierPart = 1 << 1,
  IsWhiteSpace = 1 << 2,
  IsWhiteSpaceOrLineTerminator = 1 << 3,
  IsDecimal = 1 << 4,
  IsSeparator = 1 << 5,
  IsStringLiteralLineTerminator = 1 << 6,
  Hex = 1 << 7,
  OctHexBin = 1 << 8
}

/**
 * Lookup table for mapping a codepoint to a set of flags
 */
export const AsciiCharTypes = [
  AsciiCharFlags.Unknown /* 0x00   */,
  AsciiCharFlags.Unknown /* 0x01   */,
  AsciiCharFlags.Unknown /* 0x02   */,
  AsciiCharFlags.Unknown /* 0x03   */,
  AsciiCharFlags.Unknown /* 0x04   */,
  AsciiCharFlags.Unknown /* 0x05   */,
  AsciiCharFlags.Unknown /* 0x06   */,
  AsciiCharFlags.Unknown /* 0x07   */,
  AsciiCharFlags.Unknown /* 0x08   */,
  AsciiCharFlags.Unknown /* 0x09   */,
  AsciiCharFlags.IsStringLiteralLineTerminator /* 0x0A   */,
  AsciiCharFlags.Unknown /* 0x0B   */,
  AsciiCharFlags.Unknown /* 0x0C   */,
  AsciiCharFlags.IsStringLiteralLineTerminator /* 0x0D   */,
  AsciiCharFlags.Unknown /* 0x0E   */,
  AsciiCharFlags.Unknown /* 0x0F   */,
  AsciiCharFlags.Unknown /* 0x10   */,
  AsciiCharFlags.Unknown /* 0x11   */,
  AsciiCharFlags.Unknown /* 0x12   */,
  AsciiCharFlags.Unknown /* 0x13   */,
  AsciiCharFlags.Unknown /* 0x14   */,
  AsciiCharFlags.Unknown /* 0x15   */,
  AsciiCharFlags.Unknown /* 0x16   */,
  AsciiCharFlags.Unknown /* 0x17   */,
  AsciiCharFlags.Unknown /* 0x18   */,
  AsciiCharFlags.Unknown /* 0x19   */,
  AsciiCharFlags.Unknown /* 0x1A   */,
  AsciiCharFlags.Unknown /* 0x1B   */,
  AsciiCharFlags.Unknown /* 0x1C   */,
  AsciiCharFlags.Unknown /* 0x1D   */,
  AsciiCharFlags.Unknown /* 0x1E   */,
  AsciiCharFlags.Unknown /* 0x1F   */,
  AsciiCharFlags.Unknown /* 0x20   */,
  AsciiCharFlags.Unknown /* 0x21 ! */,
  AsciiCharFlags.Unknown /* 0x22   */,
  AsciiCharFlags.Unknown /* 0x23 # */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x24 $ */,
  AsciiCharFlags.Unknown /* 0x25 % */,
  AsciiCharFlags.Unknown /* 0x26 & */,
  AsciiCharFlags.Unknown /* 0x27   */,
  AsciiCharFlags.Unknown /* 0x28   */,
  AsciiCharFlags.Unknown /* 0x29   */,
  AsciiCharFlags.Unknown /* 0x2A   */,
  AsciiCharFlags.Unknown /* 0x2B   */,
  AsciiCharFlags.Unknown /* 0x2C   */,
  AsciiCharFlags.Unknown /* 0x2D   */,
  AsciiCharFlags.Unknown /* 0x2E   */,
  AsciiCharFlags.Unknown /* 0x2F   */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x30 0 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x31 1 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x32 2 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x33 3 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x34 4 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x35 5 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x36 6 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x37 7 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x38 8 */,
  AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsDecimal | AsciiCharFlags.Hex /* 0x39 9 */,
  AsciiCharFlags.Unknown /* 0x3A   */,
  AsciiCharFlags.Unknown /* 0x3B   */,
  AsciiCharFlags.Unknown /* 0x3C < */,
  AsciiCharFlags.Unknown /* 0x3D = */,
  AsciiCharFlags.Unknown /* 0x3E > */,
  AsciiCharFlags.Unknown /* 0x3F   */,
  AsciiCharFlags.Unknown /* 0x40 @ */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x41 A */,
  AsciiCharFlags.IsIdentifierStart |
    AsciiCharFlags.IsIdentifierPart |
    AsciiCharFlags.Hex |
    AsciiCharFlags.OctHexBin /* 0x42 B */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x43 C */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x44 D */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x45 E */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x46 F */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x47 G */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x48 H */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x49 I */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x4A J */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x4B K */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x4C L */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x4D M */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x4E N */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.OctHexBin /* 0x4F O */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x50 P */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x51 Q */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x52 R */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x53 S */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x54 T */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x55 U */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x56 V */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x57 W */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.OctHexBin /* 0x58 X */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x59 Y */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x5A Z */,
  AsciiCharFlags.Unknown /* 0x5B   */,
  AsciiCharFlags.IsIdentifierStart /* 0x5C   */,
  AsciiCharFlags.Unknown /* 0x5D   */,
  AsciiCharFlags.Unknown /* 0x5E   */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.IsSeparator /* 0x5F _ */,
  AsciiCharFlags.Unknown /* 0x60   */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x61 a */,
  AsciiCharFlags.IsIdentifierStart |
    AsciiCharFlags.IsIdentifierPart |
    AsciiCharFlags.Hex |
    AsciiCharFlags.OctHexBin /* 0x62 b */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x63 c */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x64 d */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x65 e */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.Hex /* 0x66 f */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x67 g */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x68 h */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x69 i */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x6A j */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x6B k */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x6C l */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x6D m */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.OctHexBin /* 0x6E n */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.OctHexBin /* 0x6F o */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x70 p */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x71 q */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x72 r */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x73 s */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x74 t */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x75 u */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x76 v */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x77 w */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart | AsciiCharFlags.OctHexBin /* 0x78 x */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x79 y */,
  AsciiCharFlags.IsIdentifierStart | AsciiCharFlags.IsIdentifierPart /* 0x7A z */,
  AsciiCharFlags.Unknown /* 0x7B */,
  AsciiCharFlags.Unknown /* 0x7C */,
  AsciiCharFlags.Unknown /* 0x7D */,
  AsciiCharFlags.Unknown /* 0x7E */,
  AsciiCharFlags.Unknown /* 0x7F */
];
